# Site settings
title: "24fps"
email: 
description: "Analyzing the Star Wars Trilogy, scene by scene"
baseurl: ""
url: "http:24fps.me"
title_description: "Analyzing the Star Wars Original Trilogy scene by scene."
title_image: "/assets/958924.jpg"
google_analytics: 
disqus_account: "24fpsme"
github_repository: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: "24fpsm"
github_username:  
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:
patreon_username: "24fpsme"

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://patreon.com/24fpsme\">Chris Jackson</a>"
footer_right: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
